{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2017-04-09 : learning about networking using the zmq python library\n",
    "----\n",
    "Reminders : I'm trying to write a pythn-on script that run as background (daemon) on the Pi, that allow to interact with few command lines (API, maybe using zmq and/or socket) to do 3 tasks :\n",
    "- Ask the camera if it's ready to record\n",
    "- Allow the camera to answer positively or negatively\n",
    "- Ask the camera to cut down the connection  \n",
    "\n",
    "\n",
    "- [ ] Create a daemon : Canceled (Don't need one anymore)\n",
    "\n",
    "Like last week, I have connection problems to the Pi. But this time, restarting it didn't solved the problem. After talking with L. Perrinet, we didn't found where it come from.  \n",
    "I'll work on the daemon/API script until further notice.  \n",
    "More informations about zmq : http://zeromq.org/, http://api.zeromq.org/ and http://zguide.zeromq.org/py:all  \n",
    "Going further with the interactive python scripts : https://docs.python.org/2/library/thread.html#module-thread and https://docs.python.org/2/library/threading.html  \n",
    "\n",
    "The connection to the Pi works, it go a new IP : __10.164.7.213__\n",
    "\n",
    "    ssh pi@10.164.7.213\n",
    "\n",
    "To learn how zmq is working, I'm reading the (complete) documentation : http://zguide.zeromq.org/py:all  \n",
    "The zmq python library isn't installed on the pi. Problem : When trying to install it through\n",
    "\n",
    "    sudo aptitude install python3-zmq\n",
    "\n",
    "output :\n",
    "\n",
    "    E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)\n",
    "    E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?\n",
    "    W: Could not lock the cache file; this usually means that dpkg or another apt tool is already installing packages.\n",
    "    (...)\n",
    "    \n",
    "But no other apt process should be running.\n",
    "\n",
    "    ps aux | grep apt\n",
    "\n",
    "output 3 apt process running :\n",
    "\n",
    "    root       747  0.0  0.3   6184  2956 pts/0    S+   14:26   0:00 sudo apt-get upgrade\n",
    "    root       751  7.3  3.4  33656 30592 pts/0    S+   14:26   3:32 apt-get upgrade\n",
    "    pi       13293  0.0  0.1   4248  1432 pts/2    S+   15:14   0:00 grep --color=auto apt\n",
    "    \n",
    "After verification, they were launched by L. Perrinet. Waiting their end to install zmq.  \n",
    "zmq python library is succesfully installed on the pi.\n",
    "\n",
    "The following scripts works on a local machine but doesn't initiate a computer/pi connection :\n",
    "\n",
    "    '''Server side'''\n",
    "\n",
    "    import zmq\n",
    "\n",
    "    context = zmq.Context()\n",
    "    print('Connecting to client...')\n",
    "    socket = context.socket(zmq.REQ)\n",
    "    socket.connect(\"tcp://localhost:5555\")\n",
    "    print('Client connected')\n",
    "\n",
    "    for request in range(10):\n",
    "        print(\"Sending request %s...\" % request)\n",
    "        socket.send(b\"Hello\")\n",
    "\n",
    "        message = socket.recv() #Wait for next request from client\n",
    "        print(\"Received reply %s [ %s ]\" % (request, message))\n",
    "\n",
    "    print('No more requests')\n",
    "  \n",
    "\n",
    "    '''Client side'''\n",
    "\n",
    "    import time\n",
    "    import zmq\n",
    "\n",
    "    context = zmq.Context()\n",
    "    socket = context.socket(zmq.REP)\n",
    "    socket.bind(\"tcp://*:5555\")\n",
    "    print('Server connected')\n",
    "\n",
    "    while True:\n",
    "        message = socket.recv() #Wait for next request from client\n",
    "        print(\"Received request: %s\" % message)\n",
    "\n",
    "        time.sleep(2)\n",
    "        socket.send(b\"World\") #Send reply back to client\n",
    "        \n",
    "More informations about print(b\"sting\") : http://stackoverflow.com/questions/6269765/what-does-the-b-character-do-in-front-of-a-string-literal. It allow the string to be converted into bytes, necessary to be usable for other programming language.  \n",
    "\n",
    "To make these scripts works with a computer/pi connection, we need to modify the socket.connect parameters, from\n",
    "\n",
    "    socket.connect(\"tcp://localhost:5555\")\n",
    "    \n",
    "to \n",
    "\n",
    "    socket.connect(\"tcp://10.164.7.213:5555\")\n",
    "    \n",
    "Then pi output :\n",
    "\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    Received request: Hello\n",
    "    \n",
    "While computer output :\n",
    "\n",
    "    Connecting to client...\n",
    "    Client connected\n",
    "    Sending request 0...\n",
    "    Received reply 0 [ b'World' ]\n",
    "    Sending request 1...\n",
    "    Received reply 1 [ b'World' ]\n",
    "    Sending request 2...\n",
    "    Received reply 2 [ b'World' ]\n",
    "    Sending request 3...\n",
    "    Received reply 3 [ b'World' ]\n",
    "    Sending request 4...\n",
    "    Received reply 4 [ b'World' ]\n",
    "    Sending request 5...\n",
    "    Received reply 5 [ b'World' ]\n",
    "    Sending request 6...\n",
    "    Received reply 6 [ b'World' ]\n",
    "    Sending request 7...\n",
    "    Received reply 7 [ b'World' ]\n",
    "    Sending request 8...\n",
    "    Received reply 8 [ b'World' ]\n",
    "    Sending request 9...\n",
    "    Received reply 9 [ b'World' ]\n",
    "    No more requests\n",
    "\n",
    "There can be only one zmq context per process. It'll contain all the sockets of that process. Wrinting two contexts in one script means there's two process from zmq's point of view.  \n",
    "zmq interact with sockets by applying modifications : open/close, set option/get option, bind/connect and send/receive (recv) messages.  \n",
    "Client and server use different commands under certain circumstances. __Client__ is usually the most __dynamic node__, and __connect__ its sockets while __server__ is the most __static one__ and __bind__ its sockets, because it have the most stable adress. Here server will be the Pi because it is central to our network (we want to communicate with it from multiple computers).  \n",
    "zmq allows to start each node independantly, contrary to other network managers that need the server to start first.  \n",
    "Sockets are open until other notice and once bind/connected, automaticaly accept to send/receive messages (security?). \n",
    "\n",
    "Trying to add the picamera interaction into the zmq scripts...  \n",
    "A problem with the following Pi-sided line seems to induce problems :\n",
    "\n",
    "    socket.send(struct.pack('<L', stream.tell()))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2017-05-10 : merging the zmq and picamera scripts\n",
    "----\n",
    "\n",
    "- [X] Solve the file format problem\n",
    "\n",
    "The computer-sided script output : \n",
    "\n",
    "    Received reply 0 [ b'\\xf0\\xd9\\x02\\x00' ]\n",
    "    (...)\n",
    "    ---> 22     image = Image.open(image_stream)\n",
    "    (...)\n",
    "    OSError: cannot identify image file <_io.BytesIO object at 0x7f8417cb8af0>\n",
    "\n",
    "Reminds me of a previous problem I had with a file format problem : see W2_Progress_and_notes.ipynb/2017-05-05  \n",
    "But this time, the error is triggered from the first image. The problem may come from a encoding problem at the pi side.  \n",
    "\n",
    "The Pi-sided script output :\n",
    "\n",
    "    ---> socket.send(struct.pack('<L', stream.tell()))\n",
    "    File \"socket.pyx\", line 574, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5390)\n",
    "    File \"socket.pyx\", line 621, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5157)\n",
    "    File \"socket.pyx\", line 181, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2110)\n",
    "    File \"checkrc.pxd\", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6103)\n",
    "    zmq.error.ZMQError: Operation cannot be accomplished in current state\n",
    "\n",
    "The error may come from an error in the script.  \n",
    "After some researches, it is a common bug and may be caused by \"deadlocks\" (see : http://stackoverflow.com/questions/41009900/python-zmq-operation-cannot-be-accomplished-in-current-state)  \n",
    "As suggested here : http://stackoverflow.com/questions/36391495/deadlock-when-synchronizing-two-simple-python3-scripts-using-0mq-zeromq, I tried to close sockets and contexts, but it did not solved the problem.  \n",
    "\n",
    "After several hours of research, I'm still unable to solve that bug...  \n",
    "\n",
    "I tried to get rid of loops inside the Pi-sided script to simplify it, because I was wondering that zmq could only send one answer per request.  \n",
    "I might be right, because the Pi-sided error message is not showing anymore.  \n",
    "\n",
    "Now I have a problem with the data that the Pi is sending, as the computer-sided script is outputing :\n",
    "\n",
    "    (...)\n",
    "    Sending request 0...\n",
    "    Received reply 0 [ b'' ]\n",
    "    (...)\n",
    "    ---> 25     image = Image.open(image_stream)\n",
    "    (...)\n",
    "    OSError: cannot identify image file <_io.BytesIO object at 0x7f10dce2e728>\n",
    "    \n",
    "So the Pi reply seems to be an empty bytes string, instead of containing the bytes string component the captured image.\n",
    "\n",
    "- [X] Solve the empty string reply problem\n",
    "\n",
    "Scripts modified a bit to send 5 requests from computer and get 5 replies from Pi, and integrated the 'kill yourself' signal that make the Pi cut down the connection. No error except for the empty strings I get as reply. \n",
    "\n",
    "Modifying the pi-sided script to show the picture values through \n",
    "\n",
    "    print('dbkey n1', stream.getvalue())\n",
    "    \n",
    "Allow to see that picture are taken and the stream contain bytes strings. Why are these not sent correclty to the computer?  \n",
    "The data may be too big to be sent entirely? \n",
    "\n",
    "    print('dbkey n1', len(stream.getvalue()))\n",
    "    \n",
    "at Pi, output : \n",
    "\n",
    "    (...)\n",
    "    ('dbkey n1', 204193)\n",
    "    (...)\n",
    "\n",
    "while at computer, output :\n",
    "\n",
    "    (...)\n",
    "    (dbkey n1, 0)\n",
    "    \n",
    "More precisly, the byte strings seems to be lost in the Pi-sided script. See :\n",
    "\n",
    "    (...)\n",
    "    print(len(stream.getvalue()))\n",
    "    (...)\n",
    "    print(len(stream))\n",
    "    (...)\n",
    "    print(len(stream.read1(-1)))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2017-05-11 : starting to work with OpenRetina scripts\n",
    "------\n",
    "Still need to solve the empty string reply problem...  \n",
    "To resume what I know : the communication through zmq network seem to work correctly, as messages are transmitted from computer to Pi and vice versa. When asked, the picamera take pictures, as shown by :\n",
    "\n",
    "    stream = io.BytesIO()\n",
    "    (...)\n",
    "    camera.capture(stream, format='jpeg')\n",
    "\tprint('dbkey n1', len(stream.getvalue()))\n",
    "    (...)\n",
    "    \n",
    "output : \n",
    "\n",
    "    ('dbkey n1', 199757)\n",
    "    \n",
    "but just after these lines : \n",
    "\n",
    "    (...)\n",
    "\treply = stream.read1(-1)\n",
    "\tprint('dbkey n3', len(reply))\n",
    "\n",
    "\tsocket.send(reply)\n",
    "    (...)\n",
    "    \n",
    "output :\n",
    "\n",
    "    ('dbkey n3', 0)\n",
    "\n",
    "So the problem is created among these lines.  \n",
    "The error was stupid. After working a day on it, I just replaced \n",
    "    \n",
    "    (...)\n",
    "    reply = stream.read1(-1)\n",
    "    (...)\n",
    "\n",
    "by\n",
    "\n",
    "    (...)\n",
    "    reply = stream.getvalue()\n",
    "    (...)\n",
    "    \n",
    "and it finally works.  \n",
    "The capture colors are a bit weird. Close objects looks fine but some distants objects looks pink instead of purple. It may be interesting to play with camera's saturation and white balance parameters to correct these colors (as suggested here : https://raspberrypi.stackexchange.com/questions/14515/raspi-cam-color-of-image).\n",
    "\n",
    "__Reverse-engineering__ the OpenRetina project helped me understand how the various scripts are working. My own scripts can be considered as a __low-mimesis model__ of the visual system activity : the __picamera is the retina__ that __catch raw visual data__, the __internet connection__ (ethernet cable then ssh bridge) __is the optic nerve__ __transmitting the data__ and the __computer is the visual nervous central networks__ that __process the data__. \n",
    "\n",
    "Now I can start using the OpenRetina scripts directly. The final objective is to make OpenRetina to stop sending whole pictures as bytes arrays as it does now, but instead to send only active bytes locations (so 1 byte per active byte, instead of multiple containing more informations, like color captured).  \n",
    "\n",
    "L. Perrinet wrote some jupyter notebooks that'll help me to accomodate with the OpenRetina operations. The first one is __using_openretina_testing_noise.ipynb__\n",
    "\n",
    "- [X] Run the noise testing script\n",
    "\n",
    "It contain these lines : \n",
    "\n",
    "    %load_ext autoreload\n",
    "    %autoreload 2\n",
    "    \n",
    "Allowing to reload modules and refreshing imported libraries at every script start (more on : https://ipython.org/ipython-doc/3/config/extensions/autoreload.html).  \n",
    "\n",
    "    %%writefile 2017-05-12_using_openretina_testing_noise.py\n",
    "    \n",
    "Allow to automaticaly write a file with the line's box content, here a .py file executable by the Pi.\n",
    "\n",
    "    from openRetina import openRetina\n",
    "    phrs = openRetina(model=dict(layer='phrs', # label for this layer\n",
    "                                 input=['noise'], # input: can be the camera, noise, a movie (TODO)\n",
    "                                 output=['stream'] # output: can be stream, display, ...\n",
    "                                 ))\n",
    "    phrs.run()\n",
    "    \n",
    "That bloc is the main way to call the OpenRetina content, and allow to easily modify its parameters. Here\n",
    "\n",
    "    input=['noise']\n",
    "    \n",
    "call the noise section of the run() function, generating random data and allowing to check if the program is functionnal and free of errors.\n",
    "\n",
    "    !ipython3 2017-05-12_using_openretina_testing_noise.py &\n",
    "    \n",
    "Previous line allows to run the selected script in background.  \n",
    "To run these scripts, I need to install OpenRetina on the computer. The classic command line :\n",
    "\n",
    "    git clone https://github.com/laurentperrinet/openRetina\n",
    "    \n",
    "worked and I got all the folder.  \n",
    "But it seems that I can't run :\n",
    "\n",
    "    from openRetina import openRetina\n",
    "    \n",
    "because I got the output : \n",
    "\n",
    "    (...)\n",
    "    ----> 3 from openRetina import openRetina\n",
    "\n",
    "    ImportError: cannot import name 'openRetina'\n",
    "    \n",
    "I also add to (re?)install numpy for python3:\n",
    "\n",
    "    pip3 install numpy\n",
    "\n",
    "Replacing the following lines seems to solve the importing problem:\n",
    "\n",
    "    from openRetina import openRetina\n",
    "    \n",
    "by: \n",
    "\n",
    "    import openRetina \n",
    " \n",
    "But, when running : \n",
    "\n",
    "    !ipython3 2017-05-12_using_openretina_testing_noise_srv.py\n",
    "    \n",
    "I got this error as an output :\n",
    "\n",
    "    ---> 14                                  T_SIM=20))\n",
    "         15 noise.run()\n",
    "\n",
    "    TypeError: 'module' object is not callable\n",
    "    Traceback (most recent call last):\n",
    "      File \"./2017-05-12_using_openretina_testing_noise.py\", line 14, in <module>\n",
    "        output=['stream'] # output: can be stream, display, ...\n",
    "    TypeError: 'module' object is not callable\n",
    "\n",
    "Maybe the import problem is not completly resolved? Or using_openretina_testing_noise.py contain a mistake?\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2017-05-12\n",
    "----\n",
    "\n",
    "I moved all my scripts from ./Documents to ./Documents/Intership to clean my directories.\n",
    "\n",
    "- [X] Solve the uncallable module problem\n",
    "\n",
    "The problem is present as soon as we call using_openretina_testing_noise.py, as it output the same error as described previously.  \n",
    "As suggested here : http://stackoverflow.com/questions/4534438/typeerror-module-object-is-not-callable, this problem can be caused by remplacing \"from openRetina import openRetina\" by 'import openRetina\". But again, cancelling this makes the ImportError to come back.  \n",
    "\n",
    "Some internet pages suggest that I may be induced by a circular import dependencies, not permitted in python (see : http://stackoverflow.com/questions/17845366/importerror-cannot-import-name and http://stackoverflow.com/questions/1556387/circular-import-dependency-in-python).  \n",
    "After some researches, it seems that it may be induced by the openRetina folder being outside the sys.path where python modules are located. So I tried to move the openRetina folder to that path, using : \n",
    "\n",
    "    cd ../\n",
    "    sudo mv -v openRetina /usr/lib/python3.5/\n",
    "\n",
    "then inside the openRetina folder, move the src folder content to main. After doing this, errors are still here but there is some evolution. Calling :\n",
    "\n",
    "    !ipython3 2017-05-12_using_openretina_testing_noise.py\n",
    "    \n",
    "output : \n",
    "\n",
    "    \u001b]0;IPython: Documents/Intership\u0007💀  Could not load visualisation\n",
    "    Running retina on port:  5566\n",
    "    \n",
    "and calling : \n",
    "\n",
    "    !ipython3 2017-05-12_using_openretina_testing_noise_srv.py\n",
    "    \n",
    "ouput : \n",
    "\n",
    "    \u001b]0;IPython: Documents/Intership\u0007💀  Could not load visualisation\n",
    "    ---------------------------------------------------------------------------\n",
    "    TypeError                                 Traceback (most recent call last)\n",
    "    /home/albert/Documents/Intership/2017-05-12_using_openretina_testing_noise_srv.py in <module>()\n",
    "         12                                  input=['stream'], # input: can be the camera, noise, a movie (TODO)\n",
    "         13                                  output=['display'], # output: can be stream, display, capture,...\n",
    "    ---> 14                                  T_SIM=20))\n",
    "         15 noise.run()\n",
    "\n",
    "    TypeError: 'module' object is not callable\n",
    "    💀  Could not load visualisation\n",
    "    Running retina on port:  5566\n",
    "\n",
    "The errors are still there when doing a clean install :\n",
    "\n",
    "    cd ./Documents/openRetina/\n",
    "    sudo pip3 -e .\n",
    "    \n",
    "The problem don't come from the network, because the host ip isn't defined when calling so the following line automaticaly put it as localhost :\n",
    "\n",
    "     if not 'ip' in self.model.keys(): self.model['ip']='localhost'\n",
    "     \n",
    " I tried to run another script (2017-05-12_using_openretina_testing_local.ipynb) and it shows another error, I'll have to work on it later.\n",
    " \n",
    "I had to install some additionnal libraries the script needed :\n",
    "\n",
    "    pip3 install vispy --user\n",
    "    pip3 install pyglet --user\n",
    "    \n",
    "After installing these modules and reversing \"import openRetina\" to \"from openRetina import openRetina\", the script seem to work. A window poped up and showed 20s of noise signal + got multiple outputs for server (srv) side:\n",
    "\n",
    "    (...)\n",
    "    Sending request\n",
    "    Received request b'REQ'\n",
    "    Image   (1280, 720, 3) 0 254\n",
    "    (...)\n",
    "\n",
    "But something doesn't launch correctly because I have to interrupt the kernel to make the window appear. Otherwise the script seem to wait undefinitely. In addition, I got this output for srv, but it doesn't seem to bother the script execution (more information :http://stackoverflow.com/questions/33571421/ipython-notebook-shimwarning-the-ipython-kernel-package-has-been-deprecated) :\n",
    "\n",
    "    /home/albert/.local/lib/python3.5/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.\n",
    "      \"You should import from traitlets.config instead.\", ShimWarning)\n",
    "     \n",
    "It was provoqued by a human error : I was launching the client (*_using_openretina_testing_noise.py*) and the server (*_using_openretina_testing_noise-srv.py*) scripts, but the last contain the lines \n",
    "\n",
    "    import subprocess\n",
    "    p = subprocess.Popen(['./2017-05-12_using_openretina_testing_noise.py'])\n",
    "    \n",
    "that also run the client script, so the first one was waiting for a request that didn't come (more informations about the subprocess module : https://docs.python.org/2/library/subprocess.html)\n",
    "\n",
    "- [ ] Run the local testing script\n",
    "\n",
    "Next step it to run *_using_openretina_testing_local*.  \n",
    "When running, a window is poping-up but only show a black picture, so the send/rcv system seem to work, as these outputs suggest : \n",
    "\n",
    "    (...)\n",
    "    Sending request\n",
    "    Received request b'REQ'\n",
    "    (...)\n",
    "\n",
    "but the capture system may not work correctly, as these error messages suggest :\n",
    "\n",
    "    (...)\n",
    "    File \"./2017-05-12_using_openretina_testing_camera.py\", line 15, in <module>\n",
    "        phrs.run()\n",
    "      File \"/home/albert/Documents/openRetina/src/openRetina.py\", line 175, in run\n",
    "        self.camera.grab()\n",
    "      File \"/home/albert/Documents/openRetina/src/openRetina.py\", line 93, in grab\n",
    "        ret, frame_bgr = self.cap.read()\n",
    "    AttributeError: 'PhotoReceptor' object has no attribute 'cap'\n",
    "    (...)\n",
    "    \n",
    "and it force me to manually interrupt the kernel to close the window.  \n",
    "The python3 version for opencv wasn't installed on the computer (I only used the python2 version until now) :\n",
    "\n",
    "    pip3 install opencv-python --user\n",
    "    \n",
    "It didn't completly solved the problem, but the error message changed :\n",
    "\n",
    "      File \"./2017-05-12_using_openretina_testing_camera.py\", line 15, in <module>\n",
    "        phrs.run()\n",
    "      File \"/home/albert/Documents/openRetina/src/openRetina.py\", line 175, in run\n",
    "        self.camera.grab()\n",
    "      File \"/home/albert/Documents/openRetina/src/openRetina.py\", line 94, in grab\n",
    "        self.output = frame_bgr[:, :, ::-1]     #BGR to RGB\n",
    "    TypeError: 'NoneType' object is not subscriptable\n",
    "    \n",
    "Modified the concerned lines to match the program (*camera.py*) I wrote, from :\n",
    "\n",
    "            ret, frame_bgr = self.cap.read()\n",
    "            self.output = frame_bgr[:, :, ::-1]     #BGR to RGB\n",
    "    #return frame\n",
    "    \n",
    "to : \n",
    "\n",
    "            ret, frame_bgr = self.cap.read()\n",
    "            #self.output = frame_bgr[:, :, ::-1]     #BGR to RGB\n",
    "            frame = frame_bgr\n",
    "    return frame\n",
    "    \n",
    "Only made the error jump to other lines, as the script now output : \n",
    "\n",
    "      File \"./2017-05-12_using_openretina_testing_camera.py\", line 15, in <module>\n",
    "        phrs.run()\n",
    "      File \"/home/albert/Documents/openRetina/src/openRetina.py\", line 180, in run\n",
    "        data = self.code(self.camera.output)\n",
    "    AttributeError: 'PhotoReceptor' object has no attribute 'output'\n",
    "    \n",
    "Redefining the output attribute by going from :\n",
    "\n",
    "    (...)\n",
    "    self.camera.grab()\n",
    "    (...)\n",
    "    data = self.code(self.camera.output)\n",
    "    (...)\n",
    "                \n",
    "to : \n",
    "\n",
    "    (...)\n",
    "    self.frame = self.camera.grab()\n",
    "    (...)\n",
    "    data = self.code(self.frame)\n",
    "    (...)\n",
    "    \n",
    "Again, the error jumped to further lines, as the script now output :\n",
    "\n",
    "        File \"./2017-05-12_using_openretina_testing_camera.py\", line 15, in <module>\n",
    "        phrs.run()\n",
    "      File \"/home/albert/Documents/openRetina/src/openRetina.py\", line 180, in run\n",
    "        data = self.code(self.frame)\n",
    "      File \"/home/albert/Documents/openRetina/src/openRetina.py\", line 245, in code\n",
    "        image = image.astype(np.float)\n",
    "    AttributeError: 'NoneType' object has no attribute 'astype'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# outline\n",
    "------\n",
    "\n",
    "- use the openRetina library to visualize noise\n",
    "- use the openRetina library to replicate what was done in W1 & 2\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2+"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
